### ISSUE TITLE
ESP32: invalid conversion from 'void*' to 'uint8_t'

### ISSUE THREAD

**Issue by MarcDorner** [Infineon/arduino-optiga-trust-m#2]
Hi,
I came across the following problem when trying to compile an WEMOS D1 MINI ESP32 board.
Maybe someone finds the time to reproduce and verify my assumption.

# Expected Behavior
Open any Trust M example code within the Arduino IDE, choose WEMOS D1 MINI ESP32 as target and compile example successfully without any errors.

# Current Behavior
Getting three `invalid conversion from 'void*' to 'uint8_t'` errors when calling Arduino's `pinMode` and `digitalWrite` functions within pal_gpio_arduino.cpp (lines 45, 53 and 61).

# Failure Information
From my understanding C++, unlike C, does not really support/allow implicit conversions FROM `void*` types. Because the compiler for the ESP32 uses the `-fpermissive` flag, those implicit conversions are thrown as errors during compilation. And want you really want to use is actual pin number and not an address, so you need dereferencing.

# Possible Solution
Add explicit conversions and dereferencing within the pal_gpio_arduino.cpp:
- `digitalWrite(*(uint8_t*)p_gpio_context->p_gpio_hw, HIGH)`
- `digitalWrite(*(uint8_t*)p_gpio_context->p_gpio_hw, LOW);`
- `pinMode(*(uint8_t*)p_gpio_context->p_gpio_hw, OUTPUT);`

With those changes I got the examples to compile for the ESP32.

## Steps to Reproduce
1. Arduino IDE v1.8.8
2. Add ESP32 board support from https://github.com/espressif/arduino-esp32
2. Add arduino-optiga-trust-m library
3. Open any Trust M example
4. Choose WEMOS D1 MINI ESP32 as target
4. Try to compile

## Context
* Arduino IDE Version: 1.8.8
* Arduino Core for the ESP32: v1.0.4
* Operating System: Ubuntu 18.04.3

## Failure Logs
![trustmfailure](https://user-images.githubusercontent.com/47529679/67519724-be0cec00-f6a7-11e9-8d45-19b4729fdffe.png)

**Comment by ayushev** [comment]
Thank you @MarcDorner for the update!
We will make it fixed for your board as well as will include your board in the list of [Supported Devices](https://github.com/Infineon/arduino-optiga-trust-m#supported-devices)

**Comment by jaenrig-ifx** [comment]
Thank you @MarcDorner for your thorough issue report 👍 
The suggested changes are already implemented, added to the supported devices, and included in the automatic build check of Travis CI.
