### ISSUE TITLE
Import an RSA public key into a third-party application

### ISSUE THREAD

**Issue by ayushev** [Infineon/arduino-optiga-trust-m#5]
>if you give FALSE to the export_private_key parameter of the optiga_crypt_rsa_generate_keypair function, you get the public key only.

I do not want to generate key each time. I want to get the public key already generated and stored. I also want the private key will be stored safely. Can you help me with the getpublickey function?

_Originally posted by @makerstorage in https://github.com/Infineon/optiga-trust-m/issues/8#issuecomment-781999567_

**Comment by ayushev** [comment]
> I am working on the Arduino lib and looking at the examples. I test the encrypt decrypt [example](https://github.com/Infineon/arduino-optiga-trust-m/tree/master/examples/encryptDecryptData)
> Every time I run the code it generates new key pairs. I want to do that once and get the publickey
> 
> My project is to encrypt a string in the web server with PHP using the trustM public key. First thing is to get the device public key and store it in the web server (this will be done manually and keys must not change in the field.)
> 
> Server will send an encrypted message to the iot(build with trustM) the Arduino code will decrypt the message with the device private key.

thank you for the explanation, I'm however not sure, where do you struggle?
Files in the library are only examples of the underlaying [API](https://github.com/Infineon/arduino-optiga-trust-m/blob/master/src/OPTIGATrustM.h), you can jsut generate the keypair once, print out the key, import it on your webserver side and don#t do the generatation anymore. 

I might misundestood you, if this is the case, could you please elaborate where do you strugle in this example.

**Comment by makerstorage** [comment]
Thanks for the quick response. I want to specify that this is not an issue but the lack of my knowledge sorry for writing here.
I understand that I will run once the key generation function.

 It outputs something like this

Generate Key Pair RSA 1024. Store Private Key on Board ... 
[OK] | Command executed in 799 ms
Public Key  Length: 144
Public Key :
0x000000: 03 81 8d 00 30 81 89 02 81 81 00 9d df 7c 3f a3 ....0........|?.
0x000010: 34 28 5e 2d be de 05 f6 7e c7 8a ab c8 47 c2 8f 4(^-....~....G..
0x000020: 14 85 c5 30 59 59 28 8a 3c 7a 1c f3 67 5f 44 dc ...0YY(.<z..g_D.
0x000030: f6 1b c7 4e 7e c7 f2 5a e3 f4 19 51 ca 31 d0 b8 ...N~..Z...Q.1..
0x000040: a7 6e 7f a7 82 f1 5b 48 dc ab 04 b1 23 96 7b c7 .n....[H....#.{.
0x000050: ad 2b 24 e7 e6 aa 83 61 14 04 4a 82 4f 32 3f 61 .+$....a..J.O2?a
0x000060: 3e c6 6e fc e2 03 db ae 07 95 82 b1 01 ae ef 19 >.n.............
0x000070: 3f 8e cf 25 07 f0 b3 d6 08 05 ea 38 be 33 74 6a ?..%.......8.3tj
0x000080: 3a 54 78 68 b2 d9 47 67 1d f2 a1 02 03 01 00 01 :Txh..Gg........

I want to use this public key to encrypt a message with [this php function](https://www.php.net/manual/en/function.openssl-public-encrypt.php)

what is the format of the key outputs on the serial terminal. I know it is hex but do I have to convert it to PEM?
How can I do that? This function returns exception like this "openssl_public_encrypt(): key parameter is not a valid public key"

Thanks for the help in advance

**Comment by ayushev** [comment]
the output is correct, it looks like the one in the [reference](https://github.com/Infineon/optiga-trust-m/wiki/Data-format-examples#RSA-Public-Key).
You might however need to add the following bytes for the RSA1024 key if you want to import it into an openssl engine:
'30 81 9f 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00' - this is an ASN.1 Encoded sequence for the RSA1ß24 parameters of the key, they are always static for this type of the key and this size of the key.

**Comment by makerstorage** [comment]
I generated this key with my trust m IC and Arduino examples you provide. I added the bytes you sent and get this
 
`30 81 9f 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 81 8d 00 30 81 89 02 81 81 00 9d df 7c 3f a3 34 28 5e 2d be de 05 f6 7e c7 8a ab c8 47 c2 8f 14 85 c5 30 59 59 28 8a 3c 7a 1c f3 67 5f 44 dc f6 1b c7 4e 7e c7 f2 5a e3 f4 19 51 ca 31 d0 b8 a7 6e 7f a7 82 f1 5b 48 dc ab 04 b1 23 96 7b c7 ad 2b 24 e7 e6 aa 83 61 14 04 4a 82 4f 32 3f 61 3e c6 6e fc e2 03 db ae 07 95 82 b1 01 ae ef 19 3f 8e cf 25 07 f0 b3 d6 08 05 ea 38 be 33 74 6a 3a 54 78 68 b2 d9 47 67 1d f2 a1 02 03 01 00 01`

and save it as pub1.der to my computer
I try below openssl commands

```
openssl rsa -inform DER -pubin -in pub1.der -noout
openssl rsa -RSAPublicKey_in -in pub1.der -inform DER -outform PEM -out pubkey.pem -RSAPublicKey_out
```

and get this error for both commands

`unable to load Public Key
140301115995456:error:0D0680A8:asn1 encoding routines:asn1_check_tlen:wrong tag:../crypto/asn1/tasn_dec.c:1149:
140301115995456:error:0D07803A:asn1 encoding routines:asn1_item_embed_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:309:Type=X509_PUBKEY
`

**Comment by ayushev** [comment]
You can try the following:

```bash
linux$ hexdump -C pub.key
00000000  30 81 9f 30 0d 06 09 2a  86 48 86 f7 0d 01 01 01  |0..0...*.H......|
00000010  05 00 03 81 8d 00 30 81  89 02 81 81 00 9d df 7c  |......0........||
00000020  3f a3 34 28 5e 2d be de  05 f6 7e c7 8a ab c8 47  |?.4(^-....~....G|
00000030  c2 8f 14 85 c5 30 59 59  28 8a 3c 7a 1c f3 67 5f  |.....0YY(.<z..g_|
00000040  44 dc f6 1b c7 4e 7e c7  f2 5a e3 f4 19 51 ca 31  |D....N~..Z...Q.1|
00000050  d0 b8 a7 6e 7f a7 82 f1  5b 48 dc ab 04 b1 23 96  |...n....[H....#.|
00000060  7b c7 ad 2b 24 e7 e6 aa  83 61 14 04 4a 82 4f 32  |{..+$....a..J.O2|
00000070  3f 61 3e c6 6e fc e2 03  db ae 07 95 82 b1 01 ae  |?a>.n...........|
00000080  ef 19 3f 8e cf 25 07 f0  b3 d6 08 05 ea 38 be 33  |..?..%.......8.3|
00000090  74 6a 3a 54 78 68 b2 d9  47 67 1d f2 a1 02 03 01  |tj:Txh..Gg......|
000000a0  00 01                                             |..|
000000a2
linux$ openssl rsa -pubin -in pub.key -inform DER -pubout -out pubkey.pem -outform
PEM
writing RSA key
linux$ cat pubkey.pem
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCd33w/ozQoXi2+3gX2fseKq8hH
wo8UhcUwWVkoijx6HPNnX0Tc9hvHTn7H8lrj9BlRyjHQuKduf6eC8VtI3KsEsSOW
e8etKyTn5qqDYRQESoJPMj9hPsZu/OID264HlYKxAa7vGT+OzyUH8LPWCAXqOL4z
dGo6VHhostlHZx3yoQIDAQAB
-----END PUBLIC KEY-----

```

Check at first that your DER key is really a binary data. and replace the command to convert with the one I provided.


**Alternativly**, if you need to do this only once you can use a sevice like https://cryptii.com/pipes/base64-to-hex
give on the right side the binary data:
```
30 81 9f 30 0d 06 09 2a 86 48 86 f7 0d 01 01 01 05 00 03 81 8d 00 30 81 89 02 81 81 00 9d df 7c 3f a3 34 28 5e 2d be de 05 f6 7e c7 8a ab c8 47 c2 8f 14 85 c5 30 59 59 28 8a 3c 7a 1c f3 67 5f 44 dc f6 1b c7 4e 7e c7 f2 5a e3 f4 19 51 ca 31 d0 b8 a7 6e 7f a7 82 f1 5b 48 dc ab 04 b1 23 96 7b c7 ad 2b 24 e7 e6 aa 83 61 14 04 4a 82 4f 32 3f 61 3e c6 6e fc e2 03 db ae 07 95 82 b1 01 ae ef 19 3f 8e cf 25 07 f0 b3 d6 08 05 ea 38 be 33 74 6a 3a 54 78 68 b2 d9 47 67 1d f2 a1 02 03 01 00 01
```
and get as the output base64
```
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCd33w/ozQoXi2+3gX2fseKq8hHwo8UhcUwWVkoijx6HPNnX0Tc9hvHTn7H8lrj9BlRyjHQuKduf6eC8VtI3KsEsSOWe8etKyTn5qqDYRQESoJPMj9hPsZu/OID264HlYKxAa7vGT+OzyUH8LPWCAXqOL4zdGo6VHhostlHZx3yoQIDAQAB
```

form it like in the example above and you will have your public key in pem.

You can also write a python script to do this converion for you automatically.

**Comment by makerstorage** [comment]
Thanks alot @ayushev. You are great!!! 
I check the alternate method. I use the web page you suggest and get the base64 version (same as you mentioned)
I put it between begin and end key tags like below.
```
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCd33w/ozQoXi2+3gX2fseKq8hHwo8UhcUwWVkoijx6HPNnX0Tc9hvHTn7H8lrj9BlRyjHQuKduf6eC8VtI3KsEsSOWe8etKyTn5qqDYRQESoJPMj9hPsZu/OID264HlYKxAa7vGT+OzyUH8LPWCAXqOL4zdGo6VHhostlHZx3yoQIDAQAB
-----END PUBLIC KEY-----
```

I use this pem file in php openssl_public_encrypt function and get the crypted text. 
Now I will try to decode it with my trust m chip private key.

Thanks for your great support
