### ISSUE TITLE
Function to store/load custom data securely?

### ISSUE THREAD

**Issue by ONLYstcm** [Infineon/arduino-optiga-trust-m#7]
Is there an function in this repo that can be used to securely store and load data in the 10k memory? I would like to store my own custom certificates as well as some encryption keys.

**Comment by ayushev** [comment]
Hello @ONLYstcm 

there is a private function [setGenericData](https://github.com/Infineon/arduino-optiga-trust-m/blob/master/src/OPTIGATrustM.h#L793) which does exactly this, please align with the data objects map https://github.com/Infineon/optiga-trust-m/wiki/Data-and-Key-Store-Overview  
Please mind that some objects can't be written, like Private key Objects only generated.

**Comment by ONLYstcm** [comment]
Hey @ayushev, thanks for the input. I'll move forward with this info. Thanks again.
